name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy e.g., 01/01/2025)"
        required: false
        type: string
      report_date_end:
        description: "Report date end(d/MM/yyyy e.g., 31/03/2025)"
        required: false
        type: string
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate dates
        id: dates
        run: |
          # Calculate end date (yesterday)
          end_date=$(date -d "yesterday" +%-d/%m/%Y)
          
          # Calculate start date (3 months before yesterday)
          start_date=$(date -d "$end_date -3 months" +%-d/%m/%Y)
          
          # Output the full dates
          echo "start_date=$start_date" >> $GITHUB_OUTPUT
          echo "end_date=$end_date" >> $GITHUB_OUTPUT

      - name: Set date environment variables
        run: |
          if [ -n "${{ github.event.inputs.report_date_start }}" ]; then
            echo "START_DATE=${{ github.event.inputs.report_date_start }}" >> $GITHUB_ENV
          else
            echo "START_DATE=${{ steps.dates.outputs.start_date }}" >> $GITHUB_ENV
          fi
          
          if [ -n "${{ github.event.inputs.report_date_end }}" ]; then
            echo "END_DATE=${{ github.event.inputs.report_date_end }}" >> $GITHUB_ENV
          else
            echo "END_DATE=${{ steps.dates.outputs.end_date }}" >> $GITHUB_ENV
          fi

      - name: "Run PR Analytics"
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "notpyq"
          GITHUB_OWNER_FOR_ISSUE: "pyq"
          GITHUB_OWNERS_REPOS: "pyq/notpyq"
          LABELS: "PR Analytics"
          SHOW_STATS_TYPES: "timeline,workload,pr-quality,code-review-engagement,response-time"
          REVIEW_TIME_INTERVALS: "2,4,8,12,16,24"
          APPROVAL_TIME_INTERVALS: "4,8,16,24,48"
          MERGE_TIME_INTERVALS: "4,8,16,24,48"
          TOP_LIST_AMOUNT: 5
          AGGREGATE_VALUE_METHODS: "percentile,average"
          SHOW_CORRELATION_GRAPHS: true
          SHOW_ACTIVITY_TIME_GRAPHS: true
          PERCENTILE: 75
          TIMEZONE: "Asia/Shanghai"
          CORE_HOURS_START: "09:00"
          CORE_HOURS_END: "19:00"
          REPORT_DATE_START: ${{ env.START_DATE }}
          REPORT_DATE_END: ${{ env.END_DATE }}
          AMOUNT: 100
          PERIOD_SPLIT_UNIT: "months"
          USE_CHARTS: true
          ISSUE_TITLE: "PR Analytics Report (${{ env.START_DATE }} - ${{ env.END_DATE }})"

      # - name: "Display Markdown Report"
      #   run: |
      #     echo "## PR Analytics Report"
      #     echo "${{ steps.analytics.outputs.markdown }}"