name: "PR Analytics"

on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight UTC

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run PR Analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          EXECUTION_OUTCOME: markdown
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: ${{ github.event.repository.name }}
          GITHUB_OWNER_FOR_ISSUE: ${{ github.repository_owner }}
          GITHUB_OWNERS_REPOS: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
