name: "PR Analytics"
on:
  workflow_dispatch:
    # manually trigger
    inputs:
      REPORT_PERIOD:
        description: 'Report period: [unit]:value e.g. years:1, weeks:2'
        required: true
        default: "months:3"
  schedule:
    - cron: '0 1 1 * *'  # Runs at 01:00 UTC every month

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

      - name: "Run PR Analytics"
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "notpyq"
          GITHUB_OWNER_FOR_ISSUE: "pyq"
          GITHUB_OWNERS_REPOS: "pyq/notpyq"
          LABELS: "PR Analytics"
          SHOW_STATS_TYPES: "timeline,workload,pr-quality,code-review-engagement,response-time"
          REVIEW_TIME_INTERVALS: "2,4,8,12,16,24"
          APPROVAL_TIME_INTERVALS: "4,8,16,24,48"
          MERGE_TIME_INTERVALS: "4,8,16,24,48"
          TOP_LIST_AMOUNT: 5
          AGGREGATE_VALUE_METHODS: "percentile,average"
          SHOW_CORRELATION_GRAPHS: true
          SHOW_ACTIVITY_TIME_GRAPHS: true
          PERCENTILE: 75
          TIMEZONE: "Asia/Shanghai"
          REPORT_PERIOD: "${{ github.event.inputs.REPORT_PERIOD }}"
          AMOUNT: 100
          PERIOD_SPLIT_UNIT: "months"
          USE_CHARTS: true
          ISSUE_TITLE: "PR Analytics Report for ${{ github.event.inputs.REPORT_PERIOD }}"