name: "PR Analytics"
on:
  schedule:
    - cron: '0 1 1 * *'  # Runs at 01:00 UTC every month

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # - name: Calculate dates
      #   id: dates
      #   run: |
      #     # Calculate end date (yesterday)
      #     end_date=$(date -d "yesterday" +%-d/%m/%Y)
      #     END_DATE_ISO=$(date -d "yesterday" +%Y-%m-%d)
          
      #     # Calculate start date (6 months before yesterday)
      #     start_date=$(date -d "$END_DATE_ISO -6 months" +%-d/%m/%Y)
      #     START_DATE_ISO=$(date -d "$END_DATE_ISO -6 months" +%Y-%m-%d)
          
      #     # Output the full dates
      #     echo "start_date=$start_date" >> $GITHUB_OUTPUT
      #     echo "end_date=$end_date" >> $GITHUB_OUTPUT

      # - name: Set date environment variables
      #   run: |
      #     if [ -n "${{ github.event.inputs.report_date_start }}" ]; then
      #       echo "START_DATE=${{ github.event.inputs.report_date_start }}" >> $GITHUB_ENV
      #     else
      #       echo "START_DATE=${{ steps.dates.outputs.start_date }}" >> $GITHUB_ENV
      #     fi
          
      #     if [ -n "${{ github.event.inputs.report_date_end }}" ]; then
      #       echo "END_DATE=${{ github.event.inputs.report_date_end }}" >> $GITHUB_ENV
      #     else
      #       echo "END_DATE=${{ steps.dates.outputs.end_date }}" >> $GITHUB_ENV
      #     fi

      - name: "Run PR Analytics"
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "notpyq"
          GITHUB_OWNER_FOR_ISSUE: "pyq"
          GITHUB_OWNERS_REPOS: "pyq/notpyq"
          LABELS: "PR Analytics"
          SHOW_STATS_TYPES: "timeline,workload,pr-quality,code-review-engagement,response-time"
          REVIEW_TIME_INTERVALS: "2,4,8,12,16,24"
          APPROVAL_TIME_INTERVALS: "4,8,16,24,48"
          MERGE_TIME_INTERVALS: "4,8,16,24,48"
          TOP_LIST_AMOUNT: 5
          AGGREGATE_VALUE_METHODS: "percentile,average"
          SHOW_CORRELATION_GRAPHS: true
          SHOW_ACTIVITY_TIME_GRAPHS: true
          PERCENTILE: 75
          TIMEZONE: "Asia/Shanghai"
          REPORT_PERIOD: "months:3"
          AMOUNT: 100
          PERIOD_SPLIT_UNIT: "months"
          USE_CHARTS: true
          # EXECUTION_OUTCOME: "markdown"
          ISSUE_TITLE: "PR Analytics 3 Months Report (${{ env.START_DATE }} - ${{ env.END_DATE }})"