name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
        type: string
        default: "01/01/2025"  # start of the year
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
        type: string
        default: "31/12/2025"  # end of the year

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run PR Analytics"
        id: analytics
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: "notpyq"
          GITHUB_OWNER_FOR_ISSUE: "pyq"
          GITHUB_OWNERS_REPOS: "pyq/notpyq"
          LABELS: "PR Analytics"
          SHOW_STATS_TYPES: "timeline,workload,pr-quality,code-review-engagement,response-time"
          REVIEW_TIME_INTERVALS: "2,4,8,12,16,24"
          APPROVAL_TIME_INTERVALS: "4,8,16,24,48"
          MERGE_TIME_INTERVALS: "4,8,16,24,48"
          TOP_LIST_AMOUNT: 5
          AGGREGATE_VALUE_METHODS: "percentile,average"
          SHOW_CORRELATION_GRAPHS: true
          SHOW_ACTIVITY_TIME_GRAPHS: true
          PERCENTILE: 75
          TIMEZONE: "America/Los_Angeles"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          AMOUNT: 100
          PERIOD_SPLIT_UNIT: "months"
          USE_CHARTS: true
          EXECUTION_OUTCOME: "markdown"
          ISSUE_TITLE: "PR Analytics Report (${{ inputs.report_date_start }} - ${{ inputs.report_date_end }})"

      - name: "Display Markdown Report"
        run: |
          echo "## PR Analytics Report"
          echo "${{ steps.analytics.outputs.markdown }}"